---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - quota.caih.com
  resources:
  - sharedquotas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - quota.caih.com
  resources:
  - sharedquotas/finalizers
  verbs:
  - update
- apiGroups:
  - quota.caih.com
  resources:
  - sharedquotas/status
  verbs:
  - get
  - patch
  - update
