apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: shared-quota
    app.kubernetes.io/managed-by: kustomize
  name: sharedquota-manager
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: shared-quota
    app.kubernetes.io/managed-by: kustomize
  name: sharedquota-admin-role
rules:
- apiGroups:
  - quota.caih.com
  resources:
  - sharedquotas
  - sharedquotas/status
  - sharedquotas/finalizers
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  - services
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - resourcequotas
  - resourcequotas/status
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: shared-quota
    app.kubernetes.io/managed-by: kustomize
  name: sharedquota-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sharedquota-admin-role
subjects:
- kind: ServiceAccount
  name: sharedquota-manager
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sharedquota-controller
  namespace: kube-system
  labels:
    app: sharedquota-controller
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sharedquota-controller
  template:
    metadata:
      labels:
        app: sharedquota-controller
    spec:
      serviceAccountName: sharedquota-manager
      containers:
      - name: sharedquota-controller
        image: ghcr.io/caihcloud/shared-quota-controller:latest
        imagePullPolicy: IfNotPresent
        command:
        - /manager
        volumeMounts:
        - name: webhook-certs
          mountPath: /tmp/k8s-webhook-server/serving-certs # Webhook 证书默认路径
          readOnly: true
      volumes:
      - name: webhook-certs
        secret:
          secretName: sharedquota
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - operator: In
                  key: app
                  values:
                  - sharedquota-controller
              topologyKey: kubernetes.io/hostname
            weight: 1
---
apiVersion: v1
kind: Service
metadata:
  name: sharedquota-webhook
  namespace: kube-system
  labels:
    app: sharedquota-webhook
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    app: sharedquota-controller
