name: build_push
on:
  release:
    types: [ published ]

jobs:
  build_push:
    name: Build docker
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to the GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Resolve Tag
      id: resolve_tag
      run: |
        TAG_NAME="${GITHUB_REF##*/}"
        # Remove the 'v' prefix if it exists
        TAG_NAME="${TAG_NAME#v}"
        echo "TAG_NAME=$TAG_NAME" >> $GITHUB_OUTPUT

    - name: Build And Push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        platforms: linux/amd64
        tags: |
          ghcr.io/${{ env.GHCR_ORG }}/${{ env.GITHUB_REPOSITORY_NAME_PART }}-controller:v${{ steps.resolve_tag.outputs.TAG_NAME }}
          ghcr.io/${{ env.GHCR_ORG }}/${{ env.GITHUB_REPOSITORY_NAME_PART }}-controller:latest
    env:
      GHCR_ORG: ${{ github.repository_owner }}
      GITHUB_REPOSITORY_NAME_PART: ${{ github.event.repository.name }}
